// Generated by CoffeeScript 1.8.0
angular.module('myApp', ['ui.router', 'ui.bootstrap', 'ngRoute', 'ngResource', 'myApp.admin', 'myApp.util', 'myApp.blog']).config([
  '$locationProvider', '$stateProvider', '$urlRouterProvider', function($locationProvider, $stateProvider, $urlRouterProvider) {
    $urlRouterProvider.otherwise('/home');
    return $stateProvider.state('home', {
      url: '/home',
      templateUrl: 'welcome.html'
    });
  }
]).controller('navCtrl', [
  '$scope', '$location', function($scope, $location) {
    return $scope.isActive = (function(_this) {
      return function(viewLocation) {
        return viewLocation === $location.path();
      };
    })(this);
  }
]);
