// Generated by CoffeeScript 1.8.0
var tkRating, tkRatingCtrl;

tkRating = function() {
  var rating;
  rating = {
    scope: {
      value: "=",
      id: "="
    },
    require: "tkRating",
    templateUrl: "/modules/util/tk-rating/rating.html",
    controller: "tkRatingCtrl",
    link: function(scope, element, attributes, controller) {
      var max, min;
      min = parseInt(attributes.min || "1");
      max = parseInt(attributes.max || "5");
      return controller.init(min, max);
    }
  };
  return rating;
};

tkRatingCtrl = function($scope, BlogService) {
  this.init = (function(_this) {
    return function(min, max) {
      $scope.preview = -1;
      return $scope.stars = new Array(max - min + 1);
    };
  })(this);
  $scope.click = (function(_this) {
    return function($index) {
      $scope.value = $index + 1;
      return BlogService.get({
        id: $scope.id
      }).$promise.then(function(data) {
        data.rating = $scope.value;
        return data.$update();
      })["catch"](function(err) {
        return console.log(err);
      });
    };
  })(this);
  $scope.mouseover = (function(_this) {
    return function($index) {
      return $scope.preview = $index;
    };
  })(this);
  $scope.mouseout = (function(_this) {
    return function() {
      return $scope.preview = -1;
    };
  })(this);
  return $scope.styles = (function(_this) {
    return function($index) {
      return {
        "fa": true,
        "fa-star": $index < $scope.value,
        "fa-star-o": $index >= $scope.value,
        "starpreview": $index <= $scope.preview
      };
    };
  })(this);
};

angular.module('myApp.util').directive('tkRating', tkRating).controller('tkRatingCtrl', tkRatingCtrl);
